create table imagen(
    id int generated by default as identity,
    fecha date,
    direccion varchar(500),
    licencia varchar(500),
    duenov varchar(100),
    ruta varchar(500),
    primary key(id)
);

create table taxon(
    id varchar(20),
    nombre varchar(100),
    padre varchar(20),
    primary key(id)
);

create table nombre_comun(
    id int,
    especie_id varchar(20),
    nombre varchar(100),
    primary key(id),
    foreign key(especie_id) references taxon
);

create table usuario(
    id int generated by default as identity,
    nombre varchar(100),
    apellido varchar(100),
    pais varchar(100),
    direccion varchar(500),
    correo varchar(100),
    contra varchar(20),
    primary key(id)
);


create table  observacion(
    id int generated by default as identity,
    imagen_id int,
    usuario_id int,
    taxon_id varchar(20),
    comentario varchar(1000),
    longitud real,
    latitud real,
    fecha date,
    primary key(id),
    foreign key(imagen_id) references imagen,
    foreign key(usuario_id) references usuario,
    foreign key(taxon_id) references taxon
);

create table identificacion(
    id int generated by default as identity,
    observacion_id int,
    usuario_id int,
    taxon_id varchar(20),
    fecha date,
    primary key(id),
    foreign key(observacion_id) references observacion,
    foreign key(usuario_id) references usuario,
    foreign key(taxon_id) references taxon
);

